### ISSUE TITLE
运行最新版报错，请问这个有影响吗？

### ISSUE THREAD

**Issue by ybbhai** [haxqer/jira#37]
`   
___ FAILED PLUGIN REPORT _____________________
    
    1 plugin failed to load during Jira startup.
    
        'com.atlassian.jira.migration.jira-migration-plugin' - 'Jira Cloud Migration Assistant'  failed to load.
                Error creating bean with name 'planExecutionService' defined in URL [bundle://ff1ffbbd-b499-4a31-af61-f81ad039855b_93.0:1/com/atlassian/jira/migration/execution/PlanExecutionService.class]: Unsatisfied dependency expressed through constructor parameter 5; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'preflightService' defined in URL [bundle://ff1ffbbd-b499-4a31-af61-f81ad039855b_93.0:1/com/atlassian/jira/migration/preflight/PreflightService.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'asyncCheckExecutor' defined in URL [bundle://ff1ffbbd-b499-4a31-af61-f81ad039855b_93.0:1/com/atlassian/jira/migration/preflight/AsyncCheckExecutor.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'preflightCheckLookup' defined in URL [bundle://ff1ffbbd-b499-4a31-af61-f81ad039855b_93.0:1/com/atlassian/jira/migration/preflight/PreflightCheckLookup.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'advancedRoadmapsOutdatedCheck' defined in URL [bundle://ff1ffbbd-b499-4a31-af61-f81ad039855b_93.0:1/com/atlassian/jira/migration/preflight/AdvancedRoadmapsOutdatedCheck.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.atlassian.jira.migration.preflight.AdvancedRoadmapsOutdatedCheck]: Constructor threw exception; nested exception is java.lang.IllegalArgumentException
                        Error creating bean with name 'preflightService' defined in URL [bundle://ff1ffbbd-b499-4a31-af61-f81ad039855b_93.0:1/com/atlassian/jira/migration/preflight/PreflightService.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'asyncCheckExecutor' defined in URL [bundle://ff1ffbbd-b499-4a31-af61-f81ad039855b_93.0:1/com/atlassian/jira/migration/preflight/AsyncCheckExecutor.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'preflightCheckLookup' defined in URL [bundle://ff1ffbbd-b499-4a31-af61-f81ad039855b_93.0:1/com/atlassian/jira/migration/preflight/PreflightCheckLookup.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'advancedRoadmapsOutdatedCheck' defined in URL [bundle://ff1ffbbd-b499-4a31-af61-f81ad039855b_93.0:1/com/atlassian/jira/migration/preflight/AdvancedRoadmapsOutdatedCheck.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.atlassian.jira.migration.preflight.AdvancedRoadmapsOutdatedCheck]: Constructor threw exception; nested exception is java.lang.IllegalArgumentException
                                Error creating bean with name 'asyncCheckExecutor' defined in URL [bundle://ff1ffbbd-b499-4a31-af61-f81ad039855b_93.0:1/com/atlassian/jira/migration/preflight/AsyncCheckExecutor.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'preflightCheckLookup' defined in URL [bundle://ff1ffbbd-b499-4a31-af61-f81ad039855b_93.0:1/com/atlassian/jira/migration/preflight/PreflightCheckLookup.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'advancedRoadmapsOutdatedCheck' defined in URL [bundle://ff1ffbbd-b499-4a31-af61-f81ad039855b_93.0:1/com/atlassian/jira/migration/preflight/AdvancedRoadmapsOutdatedCheck.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.atlassian.jira.migration.preflight.AdvancedRoadmapsOutdatedCheck]: Constructor threw exception; nested exception is java.lang.IllegalArgumentException
                                        Error creating bean with name 'preflightCheckLookup' defined in URL [bundle://ff1ffbbd-b499-4a31-af61-f81ad039855b_93.0:1/com/atlassian/jira/migration/preflight/PreflightCheckLookup.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'advancedRoadmapsOutdatedCheck' defined in URL [bundle://ff1ffbbd-b499-4a31-af61-f81ad039855b_93.0:1/com/atlassian/jira/migration/preflight/AdvancedRoadmapsOutdatedCheck.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.atlassian.jira.migration.preflight.AdvancedRoadmapsOutdatedCheck]: Constructor threw exception; nested exception is java.lang.IllegalArgumentException
                                                Error creating bean with name 'advancedRoadmapsOutdatedCheck' defined in URL [bundle://ff1ffbbd-b499-4a31-af61-f81ad039855b_93.0:1/com/atlassian/jira/migration/preflight/AdvancedRoadmapsOutdatedCheck.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.atlassian.jira.migration.preflight.AdvancedRoadmapsOutdatedCheck]: Constructor threw exception; nested exception is java.lang.IllegalArgumentException
                                                        Failed to instantiate [com.atlassian.jira.migration.preflight.AdvancedRoadmapsOutdatedCheck]: Constructor threw exception; nested exception is java.lang.IllegalArgumentException
                                                                null
                                                                        null
    
                It was loaded from /opt/jira/atlassian-jira/WEB-INF/atlassian-bundled-plugins/jira-migration-plugin-1.7.4-629ca9440.jar
`

以及

`
15-Sep-2023 20:09:00.153 WARNING [Catalina-utility-1] org.apache.catalina.valves.StuckThreadDetectionValve.notifyStuckThreadDetected Thread [http-nio-8080-exec-1] (id=[22]) has been active for [125,838] milliseconds (since [9/15/23 8:06 PM]) to serve the same request for [http://192.168.2.199:8080/secure/SetupDatabase.jspa] and may be stuck (configured threshold for this StuckThreadDetectionValve is [120] seconds). There is/are [1] thread(s) in total that are monitored by this Valve and may be stuck.
        java.lang.Throwable
                at java.base@11.0.16/java.lang.Throwable.fillInStackTrace(Native Method)
                at java.base@11.0.16/java.lang.Throwable.fillInStackTrace(Throwable.java:787)
                at java.base@11.0.16/java.lang.Throwable.<init>(Throwable.java:292)
                at java.base@11.0.16/java.lang.Exception.<init>(Exception.java:84)
                at java.base@11.0.16/java.lang.ReflectiveOperationException.<init>(ReflectiveOperationException.java:75)
                at java.base@11.0.16/java.lang.ClassNotFoundException.<init>(ClassNotFoundException.java:82)
                at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1591)
                at org.apache.felix.framework.BundleWiringImpl.access$300(BundleWiringImpl.java:79)
                at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1976)
                at java.base@11.0.16/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
                at org.apache.felix.framework.BundleWiringImpl.getClassByDelegation(BundleWiringImpl.java:1358)
                at org.apache.felix.framework.ServiceRegistrationImpl$ServiceReferenceImpl.isAssignableTo(ServiceRegistrationImpl.java:570)
                at org.apache.felix.framework.util.Util.isServiceAssignable(Util.java:521)
                at org.apache.felix.framework.EventDispatcher.invokeServiceListenerCallback(EventDispatcher.java:974)
                at org.apache.felix.framework.EventDispatcher.fireEventImmediately(EventDispatcher.java:838)
                at org.apache.felix.framework.EventDispatcher.fireServiceEvent(EventDispatcher.java:545)
                at org.apache.felix.framework.Felix.fireServiceEvent(Felix.java:4863)
                at org.apache.felix.framework.Felix.registerService(Felix.java:3834)
                at org.apache.felix.framework.BundleContextImpl.registerService(BundleContextImpl.java:328)
                at com.atlassian.plugins.rest.module.RestModuleDescriptor.enabled(RestModuleDescriptor.java:170)
                at com.atlassian.plugin.manager.DefaultPluginManager.lambda$notifyModuleEnabled$47(DefaultPluginManager.java:1891)
                at com.atlassian.plugin.manager.DefaultPluginManager$$Lambda$577/0x00000008407e3c40.run(Unknown Source)
                at com.atlassian.plugin.manager.PluginTransactionContext.wrap(PluginTransactionContext.java:63)
                at com.atlassian.plugin.manager.DefaultPluginManager.notifyModuleEnabled(DefaultPluginManager.java:1887)
                at com.atlassian.plugin.manager.DefaultPluginManager.lambda$enableConfiguredPluginModule$32(DefaultPluginManager.java:1632)
                at com.atlassian.plugin.manager.DefaultPluginManager$$Lambda$568/0x00000008407cd040.get(Unknown Source)
                at com.atlassian.plugin.manager.PluginTransactionContext.wrap(PluginTransactionContext.java:72)
                at com.atlassian.plugin.manager.DefaultPluginManager.enableConfiguredPluginModule(DefaultPluginManager.java:1616)
                at com.atlassian.plugin.manager.DefaultPluginManager.lambda$enableConfiguredPluginModules$31(DefaultPluginManager.java:1607)
                at com.atlassian.plugin.manager.DefaultPluginManager$$Lambda$576/0x00000008407e3840.get(Unknown Source)
                at com.atlassian.plugin.manager.PluginTransactionContext.wrap(PluginTransactionContext.java:72)
                at com.atlassian.plugin.manager.DefaultPluginManager.enableConfiguredPluginModules(DefaultPluginManager.java:1604)
                at com.atlassian.plugin.manager.DefaultPluginManager.lambda$enableDependentPlugins$24(DefaultPluginManager.java:1259)
                at com.atlassian.plugin.manager.DefaultPluginManager$$Lambda$525/0x000000084075b840.run(Unknown Source)
                at com.atlassian.plugin.manager.PluginTransactionContext.wrap(PluginTransactionContext.java:63)
                at com.atlassian.plugin.manager.DefaultPluginManager.enableDependentPlugins(DefaultPluginManager.java:1229)
                at com.atlassian.plugin.manager.DefaultPluginManager.lambda$addPlugins$22(DefaultPluginManager.java:1214)
                at com.atlassian.plugin.manager.DefaultPluginManager$$Lambda$520/0x000000084075d440.run(Unknown Source)
                at com.atlassian.plugin.manager.PluginTransactionContext.wrap(PluginTransactionContext.java:63)
                at com.atlassian.plugin.manager.DefaultPluginManager.addPlugins(DefaultPluginManager.java:1114)
                at com.atlassian.jira.plugin.JiraPluginManager.addPlugins(JiraPluginManager.java:165)
                at com.atlassian.plugin.manager.DefaultPluginManager.lambda$earlyStartup$5(DefaultPluginManager.java:593)
                at com.atlassian.plugin.manager.DefaultPluginManager$$Lambda$316/0x0000000840483040.run(Unknown Source)
                at com.atlassian.plugin.manager.PluginTransactionContext.wrap(PluginTransactionContext.java:63)
                at com.atlassian.plugin.manager.DefaultPluginManager.earlyStartup(DefaultPluginManager.java:528)
                at com.atlassian.jira.plugin.JiraPluginManager.earlyStartup(JiraPluginManager.java:127)
                at com.atlassian.jira.component.pico.ComponentManager$PluginSystem.earlyStartup(ComponentManager.java:676)
                at com.atlassian.jira.component.pico.ComponentManager.earlyStartPluginSystem(ComponentManager.java:243)
                at com.atlassian.jira.component.pico.ComponentManager.restart(ComponentManager.java:641)
                at com.atlassian.jira.bc.dataimport.DataImportProductionDependencies.globalRefresh(DataImportProductionDependencies.java:123)
                at com.atlassian.jira.bc.dataimport.DefaultDataImportService.globalRefresh(DefaultDataImportService.java:910)
                at com.atlassian.jira.bc.dataimport.DefaultDataImportService.restartJira(DefaultDataImportService.java:867)
                at com.atlassian.jira.bc.dataimport.DefaultDataImportService.performImport(DefaultDataImportService.java:748)
                at com.atlassian.jira.bc.dataimport.DefaultDataImportService.doImport(DefaultDataImportService.java:323)
                at com.atlassian.jira.startup.DatabaseInitialImporter.importInitialData(DatabaseInitialImporter.java:57)
                at com.atlassian.jira.startup.DatabaseInitialImporter.importInitialData(DatabaseInitialImporter.java:40)
                at com.atlassian.jira.startup.DatabaseInitialImporter.importInitialData(DatabaseInitialImporter.java:36)
                at com.atlassian.jira.web.action.setup.SetupDatabase.doExecute(SetupDatabase.java:228)
                at webwork.action.ActionSupport.execute(ActionSupport.java:165)
                at com.atlassian.jira.web.action.JiraWebActionSupport.execute(JiraWebActionSupport.java:1382)
                at webwork.interceptor.DefaultInterceptorChain.proceed(DefaultInterceptorChain.java:39)
                at webwork.interceptor.NestedInterceptorChain.proceed(NestedInterceptorChain.java:31)
                at webwork.interceptor.ChainedInterceptor.intercept(ChainedInterceptor.java:16)
                at webwork.interceptor.DefaultInterceptorChain.proceed(DefaultInterceptorChain.java:35)
                at webwork.dispatcher.GenericDispatcher.executeAction(GenericDispatcher.java:225)
                at webwork.dispatcher.GenericDispatcher.executeAction(GenericDispatcher.java:154)
                at com.atlassian.jira.web.dispatcher.JiraWebworkActionDispatcher.service(JiraWebworkActionDispatcher.java:141)
                at javax.servlet.http.HttpServlet.service(HttpServlet.java:623)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:209)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
                at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
                at com.atlassian.jira.web.filters.JiraLastFilter.lambda$doFilter$0(JiraLastFilter.java:39)
                at com.atlassian.jira.web.filters.JiraLastFilter$$Lambda$674/0x00000008408a6040.doFilter(Unknown Source)
                at com.atlassian.jira.web.filters.steps.ChainedFilterStepRunner.doFilter(ChainedFilterStepRunner.java:74)
                at com.atlassian.jira.web.filters.JiraLastFilter.doFilter(JiraLastFilter.java:36)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
                at com.atlassian.core.filters.HeaderSanitisingFilter.doFilter(HeaderSanitisingFilter.java:37)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
                at com.atlassian.plugin.servlet.filter.IteratingFilterChain.doFilter(IteratingFilterChain.java:39)
                at com.atlassian.plugin.servlet.filter.ServletFilterModuleContainerFilter.doFilter(ServletFilterModuleContainerFilter.java:56)
                at com.atlassian.plugin.servlet.filter.ServletFilterModuleContainerFilter.doFilter(ServletFilterModuleContainerFilter.java:44)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
                at com.atlassian.jira.web.filters.MobileAppRequestFilter.doFilter(MobileAppRequestFilter.java:36)
                at com.atlassian.core.filters.AbstractHttpFilter.doFilter(AbstractHttpFilter.java:32)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
                at com.atlassian.jira.web.filters.accesslog.AccessLogFilter.executeRequest(AccessLogFilter.java:93)
                at com.atlassian.jira.web.filters.accesslog.AccessLogFilter.doFilter(AccessLogFilter.java:79)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
                at com.opensymphony.sitemesh.webapp.SiteMeshFilter.obtainContent(SiteMeshFilter.java:181)
                at com.opensymphony.sitemesh.webapp.SiteMeshFilter.doFilter(SiteMeshFilter.java:85)
                at com.atlassian.jira.web.filters.SitemeshPageFilter.doFilter(SitemeshPageFilter.java:112)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
                at com.atlassian.jira.web.filters.pagebuilder.PageBuilderFilter.doFilter(PageBuilderFilter.java:81)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
                at com.atlassian.jira.web.filters.CommittedResponseHtmlErrorRecoveryFilter.doFilter(CommittedResponseHtmlErrorRecoveryFilter.java:55)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
                at com.atlassian.plugin.servlet.filter.IteratingFilterChain.doFilter(IteratingFilterChain.java:39)
                at com.atlassian.plugin.servlet.filter.ServletFilterModuleContainerFilter.doFilter(ServletFilterModuleContainerFilter.java:56)
                at com.atlassian.plugin.servlet.filter.ServletFilterModuleContainerFilter.doFilter(ServletFilterModuleContainerFilter.java:44)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
                at com.atlassian.jira.security.xsrf.XsrfTokenAdditionRequestFilter.doFilter(XsrfTokenAdditionRequestFilter.java:46)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
                at com.atlassian.jira.web.filters.MauEventFilter.doFilter(MauEventFilter.java:49)
                at com.atlassian.core.filters.AbstractHttpFilter.doFilter(AbstractHttpFilter.java:32)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
                at com.atlassian.jira.security.JiraSecurityFilter.lambda$doFilter$0(JiraSecurityFilter.java:66)
                at com.atlassian.jira.security.JiraSecurityFilter$$Lambda$668/0x00000008408a7840.doFilter(Unknown Source)
                at com.atlassian.seraph.filter.SecurityFilter.doFilter(SecurityFilter.java:242)
                at com.atlassian.jira.security.JiraSecurityFilter.doFilter(JiraSecurityFilter.java:64)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
                at com.atlassian.security.auth.trustedapps.filter.TrustedApplicationsFilter.doFilter(TrustedApplicationsFilter.java:94)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
                at com.atlassian.seraph.filter.BaseLoginFilter.doFilter(BaseLoginFilter.java:148)
                at com.atlassian.jira.web.filters.JiraLoginFilter.doFilter(JiraLoginFilter.java:77)
                at com.atlassian.core.filters.AbstractHttpFilter.doFilter(AbstractHttpFilter.java:32)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
                at com.atlassian.plugin.servlet.filter.IteratingFilterChain.doFilter(IteratingFilterChain.java:39)
                at com.atlassian.plugin.servlet.filter.ServletFilterModuleContainerFilter.doFilter(ServletFilterModuleContainerFilter.java:56)
                at com.atlassian.plugin.servlet.filter.ServletFilterModuleContainerFilter.doFilter(ServletFilterModuleContainerFilter.java:44)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
                at com.atlassian.util.profiling.filters.RequestProfilingFilter.doFilter(RequestProfilingFilter.java:69)
                at com.atlassian.jira.web.filters.JIRAProfilingFilter.doFilter(JIRAProfilingFilter.java:29)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
                at com.atlassian.jira.web.filters.johnson.JiraJohnson503Filter.doFilter(JiraJohnson503Filter.java:79)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
                at com.atlassian.jira.web.filters.johnson.JiraJohnsonFilter.doFilter(JiraJohnsonFilter.java:72)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
                at org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:176)
                at org.tuckey.web.filters.urlrewrite.RuleChain.doRules(RuleChain.java:145)
                at org.tuckey.web.filters.urlrewrite.UrlRewriter.processRequest(UrlRewriter.java:92)
                at org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:389)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
                at com.atlassian.jira.servermetrics.CorrelationIdPopulatorFilter.doFilter(CorrelationIdPopulatorFilter.java:30)
                at com.atlassian.core.filters.AbstractHttpFilter.doFilter(AbstractHttpFilter.java:32)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
                at com.atlassian.plugin.servlet.filter.IteratingFilterChain.doFilter(IteratingFilterChain.java:39)
                at com.atlassian.plugin.servlet.filter.ServletFilterModuleContainerFilter.doFilter(ServletFilterModuleContainerFilter.java:56)
                at com.atlassian.plugin.servlet.filter.ServletFilterModuleContainerFilter.doFilter(ServletFilterModuleContainerFilter.java:44)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
                at com.atlassian.jira.web.filters.steps.ChainedFilterStepRunner.doFilter(ChainedFilterStepRunner.java:74)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
                at com.atlassian.core.filters.cache.AbstractCachingFilter.doFilter(AbstractCachingFilter.java:31)
                at com.atlassian.core.filters.AbstractHttpFilter.doFilter(AbstractHttpFilter.java:32)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
                at com.atlassian.core.filters.encoding.AbstractEncodingFilter.doFilter(AbstractEncodingFilter.java:39)
                at com.atlassian.core.filters.AbstractHttpFilter.doFilter(AbstractHttpFilter.java:32)
                at com.atlassian.jira.web.filters.JiraStaticResourceAwareEncodingFilter.doFilterInternal(JiraStaticResourceAwareEncodingFilter.java:20)
                at com.atlassian.jira.web.filters.AbstractStaticResourceAwareFilter.doFilter(AbstractStaticResourceAwareFilter.java:59)
                at com.atlassian.core.filters.AbstractHttpFilter.doFilter(AbstractHttpFilter.java:32)
                at com.atlassian.jira.web.filters.PathMatchingEncodingFilter.doFilter(PathMatchingEncodingFilter.java:41)
                at com.atlassian.core.filters.AbstractHttpFilter.doFilter(AbstractHttpFilter.java:32)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
                at com.atlassian.jira.web.filters.MultipartBoundaryCheckFilter.doFilter(MultipartBoundaryCheckFilter.java:36)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
                at com.atlassian.jira.servermetrics.MetricsCollectorFilter.doFilter(MetricsCollectorFilter.java:25)
                at com.atlassian.core.filters.AbstractHttpFilter.doFilter(AbstractHttpFilter.java:32)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
                at com.atlassian.jira.web.filters.steps.ChainedFilterStepRunner.doFilter(ChainedFilterStepRunner.java:74)
                at com.atlassian.jira.web.filters.JiraFirstFilter.doFilter(JiraFirstFilter.java:61)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
                at com.atlassian.gzipfilter.GzipFilter.doFilterInternal(GzipFilter.java:115)
                at com.atlassian.gzipfilter.GzipFilter.doFilter(GzipFilter.java:92)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
                at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
                at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
                at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:481)
                at org.apache.catalina.valves.StuckThreadDetectionValve.invoke(StuckThreadDetectionValve.java:188)
                at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
                at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
                at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
                at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:673)
                at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
                at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390)
                at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
                at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:926)
                at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1791)
                at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
                at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
                at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
                at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
                at java.base@11.0.16/java.lang.Thread.run(Thread.java:829)
2023-09-15 20:09:00,819+0800 http-nio-8080-exec-1 INFO anonymous 1206x214x1 n1eve7 192.168.2.102 /secure/SetupDatabase.jspa [c.a.upgrade.core.DefaultUpgradeTaskFactoryProcessor] Upgrade task [factory=com.atlassian.jira.jira-issue-nav-components,buildNumber=1] completed in 11 milliseconds
`

**Comment by haxqer** [comment]
'Jira Cloud Migration Assistant'  failed to load.
这个插件是云端迁移插件，可以忽略。

StuckThread 
是Setup过程时间较长，只要能安装成功，这个可以忽略。
